apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: __NAMESPACE__
spec:
  selector:
    app: spark-master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
