#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"

WORKER_REPLICAS="${SPARK_WORKER_REPLICAS:-4}"
MASTER_CPUS="${SPARK_MASTER_CPUS:-1.0}"
MASTER_MEMORY="${SPARK_MASTER_MEMORY:-1g}"
WORKER_CORES="${SPARK_WORKER_CORES:-1}"
WORKER_MEMORY="${SPARK_WORKER_MEMORY:-4g}"
WORKER_CPUS_LIMIT="${SPARK_WORKER_CPUS_LIMIT:-1.0}"
WORKER_MEMORY_LIMIT="${SPARK_WORKER_MEMORY_LIMIT:-$WORKER_MEMORY}"

export SPARK_MASTER_CPUS
export SPARK_MASTER_MEMORY
export SPARK_WORKER_CORES
export SPARK_WORKER_MEMORY
export SPARK_WORKER_CPUS_LIMIT
export SPARK_WORKER_MEMORY_LIMIT

echo "⚙️  Spark master: ${MASTER_CPUS} CPU, ${MASTER_MEMORY} RAM"
echo "⚙️  Spark workers: ${WORKER_REPLICAS} x ${WORKER_CORES} core(s), ${WORKER_MEMORY} RAM"

docker compose -f "$COMPOSE_FILE" up -d --scale spark-worker="$WORKER_REPLICAS"
